### ISSUE TITLE
Doesn't work using cs 1.6 models

### ISSUE THREAD

**Issue by Cads182** [wootguy/modelguy#1]
I tried merging hostage.mdl, they where merged but doesn't works, HLMV doesn't open it, and in game crashes.
[hostage.zip](https://github.com/wootguy/modelguy/files/6176736/hostage.zip)

**Comment by wootguy** [comment]
This tool is mostly obsolete now that HLAM can do everything this program can (except texture cropping). HLAM automatically merges models on save, and it works for that hostage model.

https://github.com/Solokiller/HL_Tools/releases/tag/HLAM-V1.1.0-alpha005

**Comment by Cads182** [comment]
Oh ok, thanks for the info!

**Comment by wootguy** [comment]
Bad news. It turns out any model with external sequences may have been corrupted by this tool after merging. Too much data was deleted from the result model, and that data could be anything (texture data, vertex data, animations, etc.). Oopsie whoopsie.
